---
type: l3leaf

# L3 Leaf switch group
l3leaf:
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: vEOS-lab
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.118.0.0/24
    # Offset all assigned loopback IP addresses.
    # Required when the < loopback_ipv4_pool > is same for 2 different node_types (like spine and l3leaf) to avoid over-lapping IPs.
    # For example, set the minimum offset l3leaf.defaults.loopback_ipv4_offset: < total # spine switches > or vice versa.
    loopback_ipv4_offset: 2
    # Definition of pool of IPs to be used as Virtual Tunnel EndPoint (VXLAN origin and destination IPs)
    vtep_loopback_ipv4_pool: 10.118.1.0/25 
    # Ansible hostname of the devices used to establish neighborship (IP assignments and BGP peering)
    uplink_switches: ['dc1-spine1', 'dc1-spine2']
    # Definition of pool of IPs to be used in P2P links
    uplink_ipv4_pool: 10.255.255.0/26
    # Definition of pool of IPs to be used for MLAG peer-link connectivity
    mlag_peer_ipv4_pool: 10.118.4.248/29
    # iBGP Peering between MLAG peers
    mlag_peer_l3_ipv4_pool: 10.118.4.244/27
    # Virtual router mac for VNIs assigned to Leaf switches in format xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp

# If two nodes (and only two) are in the same node_group, they will automatically form an MLAG pair
  node_groups:
    # Definition of a node group that will include two devices in MLAG.
    # Definitions under the group will be inherited by both nodes in the group
    - group: FE_LEAF
      # ASN to be used by BGP for the group. Both devices in the MLAG pair will use the same BGP ASN
      bgp_as: 65371
      nodes:
        # Definition of hostnames under the node_group
        - name: KDC-AR7508R3-PCS-FELEAF1
          id: 1
          mgmt_ip: 10.118.5.16/24
          # Definition of the port to be used in the uplink device facing this device.
          # Note that the number of elements in this list must match the length of 'uplink_switches' as well as 'uplink_interfaces'
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
        - name: KDC-AR7508R3-PCS-FELEAF2
          id: 2
          mgmt_ip: 10.118.5.17/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
    - group: BE_LEAF
      bgp_as: 65372
      filter:
        tags: [BE-Leaf]
      nodes:
        - name: KDC-AR7060X6-PCS-BELEAF1
          filter:
            deny_vrfs: [PCS-MPLS-INTRANET,PCS-SHARED-INTERNET]
          id: 3
          mgmt_ip: 10.118.5.116/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        - name: KDC-AR7060X6-PCS-BELEAF2
          id: 4
          filter:
            deny_vrfs: [PCS-MPLS-INTRANET,PCS-SHARED-INTERNET]
          mgmt_ip: 10.118.5.117/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
