---
# Common AVD group variables
fabric_name: FABRIC

# Generate CSVs with fabric link info.
eos_designs_documentation:
  topology_csv: true
  p2p_links_csv: true

# Define underlay and overlay routing protocol to be used
underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp

# Local users
aaa_settings:
  tacacs:
    servers:
      - host: 10.101.100.50
        groups: [PCSAUTHGRP]
        key: 0230405D350E187306465A1D16
      - host: 10.100.100.50
        groups: [PCSAUTHGRP]
        key: 03321F0D3807361E04014A0104
  local_users:
    # Username with no password configured
    - name: admin
      privilege: 15
      role: network-admin
      no_password: true
    # Username with a password
    - name: arista
      privilege: 15
      role: network-admin
      sha512_password: "$6$Enl0WfE32FthwyiJ$yTyGaEJ2uPKLU.F7314YtB7J1jrzrMi7ogXIRTEHQfLdLgKWWmr1UvNlZLN6AyuxET7G5aH3AI9OYRzxVTkB1."
  authentication:
    login:
      default: group PCSAUTHGRP local
      # Console authentication method(s) as a string.
      # Examples:
      # - "group tacacs+ local"
      # - "group MYGROUP none"
      console: local group PCSAUTHGRP
    enable:
      default: group PCSAUTHGRP local
  authorization:
    exec: 
      default: group PCSAUTHGRP local
    commands:
      all_default: group PCSAUTHGRP local
  accounting:
    exec: 
      default: 
        type: "start-stop"
        methods:
          - method: group
            group: PCSAUTHGRP local
    commands:
      default:
        - commands: all
          type: "start-stop"
          methods:
            - method: group
              group: PCSAUTHGRP
# BGP peer groups passwords
bgp_peer_groups:
  # all passwords set to "arista"
  evpn_overlay_peers:
    password: Q4fqtbqcZ7oQuKfuWtNGRQ==
  ipv4_underlay_peers:
    password: 7x4B4rnJhZB438m9+BrBfQ==
  mlag_ipv4_underlay_peer:
    password: 4b21pAdCvWeAqpcKDFMdWw==
# P2P interfaces MTU, includes VLANs 4093 and 4094 that are over peer-link
# If you're running vEOS-lab or cEOS, you should use MTU of 1500 instead as shown in the following line
p2p_uplinks_mtu: 9214

# Set default uplink, downlink, and MLAG interfaces based on node type
default_interfaces:
  - types: [spine]
    platforms: [default]
    uplink_interfaces: [Ethernet1-2]
    downlink_interfaces: [Ethernet1-8]
  - types: [l3leaf]
    platforms: [default]
    uplink_interfaces: [Ethernet1-2]
    mlag_interfaces: [Ethernet3-4]
    downlink_interfaces: [Ethernet8]
  - types: [l2leaf]
    platforms: [default]
    uplink_interfaces: [Ethernet1-2]

# CloudVision Portal definitions
cv_settings:
  onprem_clusters:
    - name: primary
      servers:
        - name: 10.113.5.1
  terminattr:
    disable_aaa: true

# DNS Server
dns_settings:
  servers:
    - ip_address: 10.113.200.12
    - ip_address: 10.118.200.12

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp_settings:
  server_vrf: PCS-NETINFRA-OOB
  servers:
    - name: 10.113.200.3
    - name: 10.118.200.3