---
# Common AVD group variables
fabric_name: FABRIC
#BGP
bgp_distance:
  external_routes: 20
  internal_routes: 200
  local_routes: 200

bgp_graceful_restart:
  # Enable or disable graceful-restart for all BGP peers.
  enabled: true
# Generate CSVs with fabric link info.
eos_designs_documentation:
  topology_csv: true
  p2p_links_csv: true

# Define underlay and overlay routing protocol to be used
underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp
# Local users
aaa_settings:
  tacacs:
    servers:
      - host: 10.101.100.50
        groups: [PCSAUTHGRP]
        key: 0230405D350E187306465A1D16
      - host: 10.100.100.50
        groups: [PCSAUTHGRP]
        key: 03321F0D3807361E04014A0104
  local_users:
    # Username with no password configured
    - name: admin
      privilege: 15
      role: network-admin
      no_password: true
    # Username with a password
    - name: arista
      privilege: 15
      role: network-admin
      sha512_password: "$6$Enl0WfE32FthwyiJ$yTyGaEJ2uPKLU.F7314YtB7J1jrzrMi7ogXIRTEHQfLdLgKWWmr1UvNlZLN6AyuxET7G5aH3AI9OYRzxVTkB1."
  authentication:
    login:
      default: group PCSAUTHGRP local
      # Console authentication method(s) as a string.
      # Examples:
      # - "group tacacs+ local"
      # - "group MYGROUP none"
      console: local group PCSAUTHGRP
    enable:
      default: group PCSAUTHGRP local
  authorization:
    exec: 
      default: group PCSAUTHGRP local
    commands:
      all_default: group PCSAUTHGRP local
  accounting:
    exec: 
      default: 
        type: "start-stop"
        methods:
          - method: group
            group: PCSAUTHGRP
    commands:
      default:
        - commands: all
          type: "start-stop"
          methods:
            - method: group
              group: PCSAUTHGRP
# BGP peer groups passwords
bgp_peer_groups:
  # all passwords set to "arista"
  evpn_overlay_peers:
    password: Q4fqtbqcZ7oQuKfuWtNGRQ==
  ipv4_underlay_peers:
    password: 7x4B4rnJhZB438m9+BrBfQ==
  mlag_ipv4_underlay_peer:
    password: 4b21pAdCvWeAqpcKDFMdWw==
# P2P interfaces MTU, includes VLANs 4093 and 4094 that are over peer-link
# If you're running vEOS-lab or cEOS, you should use MTU of 1500 instead as shown in the following line
p2p_uplinks_mtu: 9214

# Set default uplink, downlink, and MLAG interfaces based on node type
default_interfaces:
  - types: [spine]
    platforms: [default]
    uplink_interfaces: []
    downlink_interfaces: [Ethernet1-8]
  - types: [l3leaf]
    platforms: [default]
    uplink_interfaces: []
    downlink_interfaces: [Ethernet6/47/1, Ethernet6/48/1,Ethernet7/39/1, Ethernet7/37/1, ]
  - types: [l2leaf]
    platforms: [default]
    uplink_interfaces: [Ethernet49-50]

# CloudVision Portal definitions
cv_settings:
  onprem_clusters:
    - name: primary
      servers:
        - name: 10.113.5.1
        - name: 10.113.5.2
        - name: 10.113.5.3
  terminattr:
    disable_aaa: true

# DNS Server
dns_domain: 'purecloud.ae'
dns_settings:
  servers:
    - ip_address: 10.113.200.12
    - ip_address: 10.118.200.12
  vrfs:
    - name: PCS-NETINFRA-OOB
# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp_settings:
  server_vrf: PCS-NETINFRA-OOB
  servers:
    - name: 10.113.200.3
    - name: 10.118.200.3

ssh_settings:
  vrfs: 
    - name: PCS-NETINFRA-OOB
      enabled: true
  idle_timeout: 15

# Clock timezone like "CET" or "US/Pacific".
timezone: Asia/Dubai

logging:
  # Console logging severity level.
  console: "warnings" 
  buffered:
    size: 100000
    level: "informational"
  format:
    timestamp: "high-resolution"
  source_interface: Management1
  vrfs:
      # VRF name.
    - name: PCS-NETINFRA-OOB
      # Source interface name.
      source_interface: Management1
      hosts:
          # Syslog server name.
        - name: 10.115.4.100

# SNMP settings.
snmp_server:
  engine_ids:
    # Engine ID in hexadecimal.
    local: f5717ffc59c065f52900
    remotes:
        # Remote engine ID in hexadecimal.
      - id: '1234567890'
        # Hostname or IP of remote engine.
        address: server1
  # SNMP contact.
  contact: Saleem Nawaz Khan
  # SNMP location.
  location: KDC
  ipv4_acls:
      # IPv4 access list name.
    - name: ACL-SNMP
      vrf: PCS-NETINFRA-OOB
  groups:

      # Group name.
    - name: group1
      version: "v3"
      authentication: "priv"
    - name: group2
      version: "v3"
      authentication: "priv"
  users:
      # Username.
    - name: SVC_ITOM.Entuity
      # Group name.
      group: group2
      version: "v3"
      # Engine ID in hexadecimal for localizing auth and/or priv.
      localized: f5717ffc59c065f52900
      # Hash algorithm.
      auth: sha256
      # Hashed authentication passphrase if localized is used else cleartext authentication passphrase.
      auth_passphrase: c2eaf023e7dc0aa65b9aea7375980a10bc7758e65e8fd36eb0494c255c945200
      # Encryption algorithm.
      priv: aes256
      # Hashed privacy passphrase if localized is used else cleartext privacy passphrase.
      priv_passphrase: c2eaf023e7dc0aa65b9aea7375980a10bc7758e65e8fd36eb0494c255c945200
  hosts:
      # Host IP address or name.
    - host: 10.115.18.81
      vrf: PCS-NETINFRA-OOB
      version: "3"
  traps:
    # Enable or disable all snmp-traps.
    enable: true
    snmp_traps:
        # Enable or disable specific snmp-traps and their sub_traps.
        # Examples:
        # - "bgp"
        # - "bgp established"
      - name: bgp
        # The trap is enabled unless this is set to false.
        enabled: true
  vrfs:
      # VRF name.
    - name: PCS-NETINFRA-OOB
      enable: true