---
type: l2leaf

l2leaf:
  defaults:
    platform: vEOS-lab
    spanning_tree_mode: mstp

  node_groups:
    - group: OOB_LEAF1
      uplink_switches: [KDC-AR7508R3-PCS-FELEAF1, KDC-AR7508R3-PCS-FELEAF2]
      nodes:
        - name: KDC-AR7010TX-PCS-OOB1
          filter:
            tags: [MGMT]
          id: 1
          mgmt_ip: 10.118.5.42/24
          inband_mgmt_vlan: 1005
          inband_mgmt_description: PureCS_Network_Infra_nodes_OOB
          inband_mgmt_ip: 10.118.5.41/24
          inband_mgmt_interface: Vlan1005
          inband_mgmt_vrf: PCS-NETINFRA-OOB
          uplink_switch_interfaces: [Ethernet6/47/1, Ethernet6/47/1]
          uplink_switch_port_channel_id: 1647
    - group: OOB_LEAF2
      uplink_switches: [KDC-AR7508R3-PCS-FELEAF1, KDC-AR7508R3-PCS-FELEAF2]
      nodes:
        - name: KDC-AR7010TX-PCS-OOB2
          filter:
            tags: [MGMT]
          id: 2
          mgmt_ip: 10.118.5.42/24
          inband_mgmt_vlan: 1005
          inband_mgmt_ip: 10.118.5.42/24
          inband_mgmt_description: PureCS_Network_Infra_nodes_OOB
          inband_mgmt_interface: Vlan1005
          inband_mgmt_vrf: PCS-NETINFRA-OOB
          uplink_switch_interfaces: [Ethernet6/48/1, Ethernet6/48/1]
          uplink_switch_port_channel_id: 1648
    - group: OOB_LEAF3
      uplink_switches: [KDC-AR7508R3-PCS-FELEAF1, KDC-AR7508R3-PCS-FELEAF2]
      nodes:
        - name: KDC-AR7010TX-PCS-OOB3
          filter:
            tags: [MGMT]
          id: 3
          mgmt_ip: 10.118.5.42/24
          inband_mgmt_vlan: 1005
          inband_mgmt_description: PureCS_Network_Infra_nodes_OOB
          inband_mgmt_ip: 10.118.5.43/24
          inband_mgmt_interface: Vlan1005
          inband_mgmt_vrf: PCS-NETINFRA-OOB
          uplink_switch_interfaces: [Ethernet7/39/1, Ethernet7/37/1]
          uplink_switch_port_channel_id: 1639