---
type: l2leaf

l2leaf:
  defaults:
    platform: vEOS-lab
    spanning_tree_mode: mstp

  node_groups:
    - group: DC1_L2_LEAF1
      uplink_switches: [KDC-AR7508R3-PCS-FELEAF1, KDC-AR7508R3-PCS-FELEAF2]
      nodes:
        - name: dc1-leaf1c
          id: 1
          mgmt_ip: 10.118.5.18/24
          uplink_switch_interfaces: [Ethernet8, Ethernet8]
    - group: DC1_L2_LEAF2
      uplink_switches: [KDC-AR7060X6-PCS-BELEAF1, KDC-AR7060X6-PCS-BELEAF2]
      nodes:
        - name: dc1-leaf2c
          id: 2
          mgmt_ip: 10.118.5.19/24
          uplink_switch_interfaces: [Ethernet8, Ethernet8]
